from dotenv import load_dotenv
load_dotenv()

import sys
sys.path.append(".")

import asyncio
from baml_client.async_client import b
from baml_client.types import Summary
from pdf_processor import PDFProcessor

async def main():
    processor = PDFProcessor()
    
    pdf_path = "data/pdfs/Optimal_Stochastic_Resource_Allocation_for_Distrib.pdf"
    paper_text = processor.extract_text_from_fisrt_N_pages(pdf_path, 2)

    # this function comes from the autogenerated "baml_client".
    # It calls the LLM you specified and handles the parsing.
    summary = await b.SummaryPaper(paper_text)

    # Fully type-checked and validated!
    assert isinstance(summary, Summary)

if __name__ == '__main__':
    asyncio.run(main())